version: "3.7"
services:
  database:
    restart: always
    image: postgres:10.1
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./portfolio-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - back-end
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - back-end

  app:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    image: portfolio-app
    volumes:
      - .:/portfolio-app
      - static_volume:/portfolio-app/staticfiles/
    depends_on:
      - database
      - redis
    entrypoint: ["/bin/bash", "-c", "/portfolio-app/docker/start_api.sh"]
    stdin_open: true
    tty: true
    networks:
      - back-end
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_HOST=database
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOST=${ALLOWED_HOST}
      - CELERY_BROKER_URL=redis://redis
      - CELERY_RESULT_BACKEND=redis://redis
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - TO_EMAIL=${TO_EMAIL}

  proxy:
    image: portfolio-nginx
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    expose:
      - "81"
    networks:
      - back-end
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/portfolio-app/static/
    restart: always

    environment:
      - VIRTUAL_HOST=hesbon.me
      - LETSENCRYPT_HOST=hesbon.me
      - VIRTUAL_PORT=81


  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.conf:/data/nginx/custom/http_top.conf
      - certs:/etc/nginx/certs
      - vhost-d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=hesbonkiptoo5600@gmail.com
    networks:
      - back-end
      - front-end
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost-d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=hesbonkiptoo5600@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy


networks:
  default:
    external:
      name: nginx-proxy

  back-end:
  front-end:
volumes:
  certs:
  vhost-d:
  html:
  acme:
  static_volume:
  database_volume:
