# Generated by Django 3.1.6 on 2021-02-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210221_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(db_index=True),
        ),
    ]
