# Generated by Django 3.1.6 on 2021-02-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210221_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category_style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
