# Generated by Django 3.1.6 on 2021-02-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_category_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail_image_url',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
    ]
