# Generated by Django 3.1.7 on 2021-02-24 06:41

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_thumbnail_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('description', tinymce.models.HTMLField()),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('fade_style', models.CharField(max_length=50)),
                ('description_style', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(db_index=True, max_length=50)),
                ('end_date', models.DateField(blank=True, db_index=True, max_length=50, null=True)),
                ('background_image_url', models.CharField(db_index=True, max_length=250)),
                ('projects', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_client_related', to='portfolio.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
