# Generated by Django 3.1.7 on 2021-02-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='client',
            name='projects',
        ),
        migrations.AddField(
            model_name='client',
            name='projects',
            field=models.ManyToManyField(related_name='portfolio_client_related', to='portfolio.Project'),
        ),
    ]
