# Generated by Django 3.1.7 on 2021-02-24 09:31

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210224_0644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-end_date']},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='roles',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='success',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
