# Generated by Django 3.1.7 on 2021-02-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20210224_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category_style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
